# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fec3d3cb66fe1df5cc62cef7d5e2c7b0c185450b1e5e99670fbcf8dbf92a54ae95949b8d4313be07e0c96f19d416e2cee72568443a9405dc9b201f7e8627f4a

test:
  secret_key_base: 2467122ddf2c81653a72532bd971c2480c34729d4941f41ec70f43f44d1b15b4d5ba13ee586e4104d6c2864620479e7c6b20f23344468069ee15e8c9b0706597

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
